fix(build_gen): use consistent names for open source package
googleapis/rules_gapic pull request #59
Opened 2021-07-01 18:06 UTC by jpoehnelt

2021-07-06 02:24 UTC, miraleung requested changes
This will affect all ~200 API teams that use build_gen, with downstream effects on GitHub and our publishing pipeline.

Could you please describe what end goal you have in mind? Let's explore ways to achieve that while minimizing the blast radius.

2021-07-06 15:06 UTC, jpoehnelt commented
Goals:

1. remove cloud from non-cloud apis
2. use consistent naming to better enable downstream tooling, not having to switch on language in my scripts to get the package name and resulting tar file
3. not having to undo changes in the build file every time buildgen is executed on the directory

> with downstream effects on GitHub and our publishing pipeline

the alias should minimize these effects. if we remove the deprecation message there should be no blast radius

2021-07-07 21:58 UTC, miraleung commented
CC @vam-google

Thanks for the context, @jpoehnelt. Since the objective of this change is primarily for a non-cloud use case, could we instead introduce a `--cloud` flag? This would default to `true`, and when set to `false`, it could produce a BUILD file with the change in this PR. WDYT?

We would like to support non-Cloud APIs as well, and these seem like different use cases. As the vast majority of our users consist of Cloud APIs, introducing a different run-mode could help address your (Geo's?) use case while maintaining existing behavior for Cloud teams.

2021-07-07 22:44 UTC, jpoehnelt commented
I'm not sure the complexity of adding a different run mode is worth it. This change should have zero impact on cloud teams.

2021-07-07 22:59 UTC, jpoehnelt commented
I guess it would change the tar output name. :/

2021-07-07 23:42 UTC, vam-google requested changes
That naming is horrible and comes from the package names produced by Artman (legacy tool used to generate these things). Unfortunately too many things are currently depending on the generated name format for each individual language (like owl-bot used to populate googleapis-gen repository, many internal tools/scripts which we are not even aware of).

In other words, I agree that the current naming is very bad, but unless somebody has capacity to fix not only current naming but everything else which already depends on this naming, I believe we have to keep it as is.

2021-07-09 08:20 UTC, vam-google requested changes
Please do not do this. This adds too many hacks to the generated file to fix a relatively minor issue with naming. Notice, this file is on the surface of all builds. People interact with it very often, it must be kept as clean as possible. Local variables and aliasing is not idiomatic for build files and in general over complicates things without providing much benefit.

Please think about it this way: if we push this change, it will sacrifice the readability of build files of all cloud in the name of Google Maps. With all respect to maps, we can't do it.

If you really need a custom template, you can specify it as a command line arg to the build file generator: https://github.com/googleapis/rules_gapic/blob/main/bazel/src/main/java/com/google/api/codegen/bazel/ArgsParser.java#L75

2021-07-09 08:20 UTC, vam-google commented on bazel/src/main/java/com/google/api/codegen/bazel/BUILD.bazel.gapic_api.mustache
> +java_gapic_assembly_gradle_pkg_deps = [
this is too verbose and non-idiomatic (to keep dependencies in a separate vairiable, and even in that chase the variable shoudd be named `_LIKE_THIS`.

2021-07-09 08:20 UTC, vam-google commented on bazel/src/test/data/googleapis/google/example/library/v1/BUILD.bazel.baseline
> +alias(
Too verbose, adds aliasing to solve the non-pretty name issue. This is too verbose.

2021-07-09 14:50 UTC, closed without merging